spring.application.name=collector

server.port=8080
logging.level.ru.yandex.practicum=TRACE

collector.kafka.producer.properties.bootstrap.servers=localhost:9092
collector.kafka.producer.properties.key.serializer=org.apache.kafka.common.serialization.StringSerializer
collector.kafka.producer.properties.value.serializer=ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer
collector.kafka.producer.topics.sensors-events=telemetry.sensors.v1
collector.kafka.producer.topics.hub-events=telemetry.hubs.v1